name: Generate and Deploy Doxygen Docs

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Install Doxygen
      run: sudo apt-get install doxygen graphviz -y
    
    - name: Generate Documentation
      run: doxygen Doxyfile
    
    - name: Commit and Push Documentation to `docs` branch
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git checkout --orphan docs
        git rm -rf .
        mv docs/* ./
        git add .
        git commit -m "Update Doxygen documentation"
        git push origin docs --force
